"""add file_size to image

Revision ID: b07bdd5abbc3
Revises: 5306cf93d1fc
Create Date: 2026-06-15 14:47:45.285861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07bdd5abbc3'
down_revision: Union[str, Sequence[str], None] = '5306cf93d1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('file_size', sa.Integer(), nullable=True))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('image', 'file_size')
    # ### end Alembic commands ###
